global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'keycloak'
    metrics_path: /metrics
    static_configs:
      - targets: ['keycloak:8080']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']

  # Add scrape configs for your microservices here
  # Example:
  # - job_name: 'api-gateway'
  #   metrics_path: /actuator/prometheus
  #   static_configs:
  #     - targets: ['api-gateway:8080']
  
  # - job_name: 'discovery-service'
  #   metrics_path: /actuator/prometheus
  #   static_configs:
  #     - targets: ['discovery-service:8761']
  
  # - job_name: 'config-service'
  #   metrics_path: /actuator/prometheus
  #   static_configs:
  #     - targets: ['config-service:8888']