eureka:
  instance:
    hostname: ${DISCOVERY_SERVER_HOSTNAME:localhost}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info
    home-page-url: /
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${DISCOVERY_SERVER_DOMAIN:http://localhost}:${DISCOVERY_SERVER_PORT:8761}/eureka/


  management:
    endpoints:
      web:
        exposure:
          include: health,info
    endpoint:
      health:
        show-details: always