spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: "users-service"
              uri: lb://users-service
              predicates:
                - Path=/users/**
              filters:
                - PrefixPath=/api/v1
server:
  port: ${GATEWAY_SERVER_PORT:8080}
