spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${USERS_DATABASE_URL:jdbc:postgresql://localhost:5432/users}
    username: ${USERS_DATABASE_USERNAME:postgres}
    password: ${USERS_DATABASE_PASSWORD:password}
server:
  port: ${USERS_SERVER_PORT:8090}

